# Generated by Django 4.2.9 on 2026-03-30 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinWheelReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('reward_type', models.CharField(choices=[('cash', 'Cash (KES)'), ('points', 'Points'), ('free_spin', 'Free Spin'), ('nothing', 'No Reward')], max_length=20)),
                ('reward_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'spin_wheel_rewards',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('survey', 'Survey'), ('signup', 'Sign Up on Partner Site'), ('social', 'Social Media Action'), ('download', 'App Download'), ('custom', 'Custom')], max_length=20)),
                ('reward_points', models.PositiveIntegerField(default=0)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('action_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_completions', models.PositiveIntegerField(blank=True, null=True)),
                ('current_completions', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='YouTubeAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('youtube_video_id', models.CharField(max_length=50)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('reward_points', models.PositiveIntegerField(default=10)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_limit_per_user', models.PositiveIntegerField(default=5)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'youtube_ads',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('ad_watch', 'Ad Watch'), ('spin_wheel', 'Spin Wheel'), ('task_completion', 'Task Completion'), ('referral_commission', 'Referral Commission'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('bonus', 'Bonus')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('proof_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='earnings.task')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='earnings.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_completions',
            },
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='earnings.spinwheelreward')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='earnings.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spin_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdWatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watch_duration', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('rewarded', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='earnings.youtubead')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='earnings.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_watches',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='transaction_user_id_9aa2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('user', 'task')},
        ),
        migrations.AddIndex(
            model_name='adwatch',
            index=models.Index(fields=['user', 'ad', 'created_at'], name='ad_watches_user_id_cfcad8_idx'),
        ),
    ]
